language: python
sudo: required
services:
- docker
env:
  matrix:
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.2.1
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.2.1
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.3.0
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.3.0
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.4.1
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.4.1
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.5.0
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.5.0
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.6.0
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.6.0
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.7.1
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.7.1
  - PYTHON_VERSION=2.7 TENSORFLOW_VERSION=1.8.0
  - PYTHON_VERSION=3.6 TENSORFLOW_VERSION=1.8.0
  global:
  - secure: oa2d5oIT4qdoc76m31f+GJiV1CNn2s99SfcfOkm1jAmkBGCtLVJN49nBV3p87mqvXxGCy2qvWvnetMH1onVsLRAiS5oLxRh1ocXfmFjhPwFThpDtt3L+le+ld5XPyJdAOHmfk2BoMkm+XEXD/GZUt6mR3cs0lAJawKt5VNGB0HmKPk18x/EXz0sFcO84BRIbGJnq7TS69m8OCqbgSaeWeiXk1RDoSCM6tiWDWzADZEaiTW39HXejAnUceajnXpvkFYV6HVOKKJ9pLAgaZh9Z858fitWW2jaNGSXhw/TU4RImEhqXED9z427JNLXvaE/Jfj40xX+UIVomIrNHI6tgWCrb13eEFzPrSta96J+QFCDOxGeziKPxiFqKOk4/rw9nMkfumPIAQxLgd7I8q/KC0Q9wayRv2IcsY1F3HUTfURi0uI3p/uFTTe8/FVncY/ouQl8bFBs5/eM4IxjMUHUkl6kIoO4TNbw9j7PPeKc1TE6p0a8RINxAAM48y9RNkbP/Qf68KyFuH7TFpL47TNNIjBnyzTumAKHN7ZKx72L+giE8wwdepdB/r2CmEwMZbXQitnXVZXuPzf/OrwjAFPQepdUJ3MmlJOOFPDCdQtgPDtkmi5XE+bDMxrsiZjr8WwHIb2aNCHXfXDUVgu+8lgOfUjCmSHjigU9Oo2VHDtJITBI=
  - secure: v8v43NaI4IT6QiPOjEr1Hwd6Zq4EpUj9aRq9H9cWKDAMSSFMpk9cqSbHgiwMBI+PMGBsKTKc8DLdYNjDa3baO9sF569tF3AR1rUxoVvohMv/tzY8q9zXV2SA4cBNpwxNet2CiARamTaNrbQLQTrjUuGWUMu2q/44p6BGeeW7XSLIgPMxkhY/dmargI5e1R7kxmXYDvbdCCatwj6GhpetkRNos6KPlZh48f6NjPVnvZ10bn7UNd7Y5aQlAgjhnq8QMaPLF1CzxZ80sg1OXtFk1vrkr336f5rkaYMLzNcCvS2K92SMykBl+MmQEiH6Qf8TYQZVmsHqRPcRUrRp58opGGAwmKCw8Q9sWIiprImjSowh6/fsbZqfqhAYWy7lQ5yfKoWHLYqRQY1HnMR5T5o9qTEJV70ml0tuzijE3ktM6pAePGRjG8ny2dpyTf3P4Mqm6FWV4UzAtTZcE7hlwRuLZPAwly+gPhki59sIlvEbDrbxWU3SDghI/YZZRYaqV0E3/3/aJt73XoUHvjrT3xCAuPi9NXvs6BtQJxjFC+3I+nb4pRvUTPBKoOTCo44q8+PIwYeCQQXDtPj8wRI6cs539YzhjdPdqEzhH+Ct9zdpbV9dQv36CffvcLwUHw5RbahN2xoXl6cZUKDzdBdQEviFKCGNkBO3HwCesM3L66h4l3I=
install:
- export REPO="ipwx/travis-tensorflow-docker"
- export TAG="py${PYTHON_VERSION:0:1}tf${TENSORFLOW_VERSION:0:3}"
- docker build -t "${REPO}:${TAG}" "${TAG}"
script:
- docker run -v "$(pwd)":"$(pwd)" -w "$(pwd)" -e PYTHON_VERSION="${PYTHON_VERSION}"
  -e TENSORFLOW_VERSION="${TENSORFLOW_VERSION}" "${REPO}:${TAG}" python tests.py
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
- docker push "${REPO}:${TAG}"
